const { error: err_log } = require('./debug')(__filename)

function error(err, meta) {
  err_log(err, meta)
  throw err
}

const err = {
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  USER_ID_REQUIRED: 'USER_ID_REQUIRED',
  ACTION_REQUIRED: 'ACTION_REQUIRED',
  UNKNOWN_ACTION: 'UNKNOWN_ACTION',
  MASTER_KEY_REQUIRED: 'MASTER_KEY_REQUIRED',
  INVALID_TEMPLATE: 'INVALID_TEMPLATE',
  CONTAINER_MISSING: 'CONTAINER_MISSING',
  TEMPLATE_MISSING: 'TEMPLATE_MISSING',
  NO_CONTAINER_INSTALLED: 'NO_CONTAINER_INSTALLED',
  MISSING_VARIABLES: 'MISSING_VARIABLES',
  BASE_INTERFACE_MISSING: 'BASE_INTERFACE_MISSING',
  REQUESTED_INTERFACE_MISSING: 'REQUESTED_INTERFACE_MISSING',
  KEYS_MISSING: 'KEYS_MISSING',
  INTERFACES_MISSING: 'INTERFACES_MISSING',
  ADMIN_STREAM_MISSING: 'ADMIN_STREAM_MISSING',
  CALL_TO_MISSING_STREAM_TEMPLATE: 'CALL_TO_MISSING_STREAM_TEMPLATE',
  STREAM_MISSING: 'STREAM_MISSING',
  BAD_INDEX: 'BAD_INDEX',
  INDEX_CREATION_FAILED: 'INDEX_CREATION_FAILED',
}

module.exports = { error, err, errors: err }
